function Hd = cheby1
%N2FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 04-Apr-2021 23:07:21

% Chebyshev Type I Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 100000;  % Sampling Frequency

Fpass1 = 5000;        % First Passband Frequency
Fstop1 = 15000;       % First Stopband Frequency
Fstop2 = 35000;       % Second Stopband Frequency
Fpass2 = 40000;       % Second Passband Frequency
Apass1 = 5;           % First Passband Ripple (dB)
Astop  = 50;          % Stopband Attenuation (dB)
Apass2 = 5;           % Second Passband Ripple (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
